#workflow start here 
name: check-pr

on:
  pull_request:
  

jobs:
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: fail if size is more than 1MB
        uses: pelotech/github-action-file-size-checker@v0.1.2
        with:
          max_file_size_kib: '100'


  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: branch-name-check
        run: |
          echo "Branch name is: ${{ github.head_ref }}"
           if [[ ! "${{ github.head_ref }}" =~ ^(feature|fix|docs)/ ]]; then
          echo "Invalid branch name. Use feature/*, fix/*, or docs/*"
          exit 1
        fi
