name: file-size-check

on:
  pull_request:
    branches:
      - main

jobs:
  filesize-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: greet
        run: echo "Hello world"
  
      - name: set file size limit
        uses: pelotech/github-action-file-size-checker@v0.1.2
        with:
          max_file_size_kib: '50'
