name: pr-lifecycle

on:
  pull_request: 
    options: [opened, closed, reopened, synchronize]

jobs:
  explore-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
    
      - name: Print which event type fired
        run: echo "The even is':' ${{ github.event.action }}"    

