name: schedule-job

on:
  schedule:
    - cron: "30 2 * * 1"
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print which schedule triggered
        run: echo "The schedule is trigger by  ${{ github.event.schedule || 'manual (workflow_dispatch)' }}" 
